import { createClient } from '@supabase/supabase-js'

const supabaseUrl = 'https:/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtbWl5bGJydGRuYXpyanVrc2d2Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NDQxNDQ1MCwiZXhwIjoyMDY5OTkwNDUwfQ.iGm30FxXRETXkk0rVn8AZGxi01NxO300VLktcVj-kYI.supabase.co'
const supabaseAnonKey = ‘eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtbWl5bGJydGRuYXpyanVrc2d2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MTQ0NTAsImV4cCI6MjA2OTk5MDQ1MH0.V2RGZLNAeG7bazLajiarPW6waEzOBLYuwLctvDsKlek'

